### ISSUE TITLE
Question Regarding Datasets for Replicating FeatLLM

### ISSUE THREAD

**Issue by 1836897243** [Sungwon-Han/FeatLLM#1]
Hello,

Thank you for your outstanding work! I am currently attempting to replicate the results from the paper and have encountered some questions regarding the datasets. Specifically, the "Cultivars" dataset is labeled as a regression dataset in the link provided in the paper. Could you please clarify how it was transformed into a binary classification dataset? Was a middle value used, or was there another method applied?

I appreciate your assistance!

**Comment by Sungwon-Han** [comment]
Thank you for your interest in our work!

As expected, the median is used to transform continuous values into binary values.
